name: Deploy
on: push
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run script
        run: |
          echo "Deploying..."
          echo "AWS_SECRET_KEY=$AWS_SECRET_ACCESS_KEY"
